version: "3.9"

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bonfire
      POSTGRES_PASSWORD: bonfire
      POSTGRES_DB: bonfire
    volumes:
      - bonfire-postgres:/var/lib/postgresql/data

volumes:
  bonfire-postgres:
